image: node:10.15.3

cache:
  paths:
    - node_modules/

before_script:
  - test -e package.json && npm install
  - hexo generate

pages:
  script:
    - hexo deploy
  artifacts:
    paths:
      - public
  only:
    - master
